export const direct = {
  text: {
    envelope: {
      id: 'fake_root_id',
      name: '2022-05-28T01:19:09.219Z_firehose',
      targetUrl: 'https://speedybot-hub.username.workers.dev',
      resource: 'messages',
      event: 'created',
      orgId: 'fake_orgId',
      createdBy:
        'Y2lzY29zcGFyazovL3VzL1BFT1BMRS85OTFjNzhjZS0yZWQ2LTQ3MzQtOWUzMS0wOGQzYTc0MTBmYzE',
      appId: 'fake_appId',
      ownedBy: 'creator',
      status: 'active',
      created: '2022-05-28T01:19:09.591Z',
      actorId: 'fake_actorId',
      data: {
        id: 'fake_id',
        roomId: 'fake_roomId',
        roomType: 'direct',
        personId: 'fake_personId',
        personEmail: 'fake_personEmail@bongo.com',
        created: '2022-05-28T13:13:26.030Z',
      },
    },
    details: {
      id: 'fake_root_id2',
      roomId: 'fake_roomId',
      roomType: 'direct',
      text: 'hi',
      personId: 'fake_personId',
      personEmail: 'fake_personEmail@bongo.com',
      created: '2022-05-28T13:13:26.030Z',
    },
    trigger: {
      type: 'message',
      id: 'fake_root_id',
      text: 'hi',
      args: ['hi'],
      message: {
        id: 'fake_root_id',
        roomId: 'fake_roomId',
        roomType: 'direct',
        text: 'hi',
        personId: 'fake_personId',
        personEmail: 'fake_personEmail@bongo.com',
        created: '2022-05-28T13:34:57.808Z',
      },
      person: {
        id: 'fake_personId',
        emails: ['fake_personEmail@bongo.com'],
        phoneNumbers: [
          {
            type: 'mobile',
            value: '+1 310-123-4567',
          },
          {
            type: 'work',
            value: '+1 310-987-6543',
          },
        ],
        displayName: 'Fake Name',
        nickName: 'Fake',
        firstName: 'Fake',
        lastName: 'Lastname',
        userName: 'fake_personEmail@bongo.com',
        avatar: 'https://avatar-prod-us-east-2.webexcontent.com/profphoto',
        orgId: 'fake_orgId',
        created: '2016-01-14T15:55:08.526Z',
        lastModified: '2016-05-19T17:44:50.859Z',
        type: 'person',
      },
      personId: 'fake_personId',
      phrase: 'hi',
    },
  },
  text_multiple_words: {
    envelope: {
      id: 'fakek_id',
      name: '2016-01-14T15:55:08.526Z',
      targetUrl: 'https://speedybot-hub.username.workers.dev',
      resource: 'messages',
      event: 'created',
      orgId: 'fake_orgId',
      createdBy: 'fake_createdBy',
      appId: 'fake_appId',
      ownedBy: 'creator',
      status: 'active',
      created: '2016-01-14T15:55:08.526Z022-06-04T06:29:16.448Z',
      actorId: 'fake_actor_id',
      data: {
        id: 'fake_id',
        roomId: 'fake_roomid',
        roomType: 'direct',
        personId: 'fake_personId',
        personEmail: 'fake_person@bongo.com',
        created: '2016-01-14T15:55:08.526Z',
      },
    },
    details: {},
    trigger: {
      type: 'message',
      id: 'fake_id',
      text: 'hi multiple words abc',
      args: ['hi', 'multiple', 'words', 'abc'],
      message: {
        id: 'fake_message_id',
        roomId: 'fake_roomId',
        roomType: 'direct',
        text: 'hi multiple words abc',
        personId: 'fake_personId',
        personEmail: 'fake_person@bongo.com',
        created: '2022-05-28T13:36:40.499Z',
      },
      person: {
        id: 'fake_id',
        emails: ['fake_person@bongo.com'],
        phoneNumbers: [
          {
            type: 'mobile',
            value: '+1 310-123-4567',
          },
          {
            type: 'work',
            value: '+1 310-654-3210',
          },
        ],
        displayName: 'Fake Person',
        nickName: 'Fake',
        firstName: 'Fake',
        lastName: 'Person',
        userName: 'fake_person@bongo.com',
        avatar: 'https://avatar-prod-us-east-2.webexcontent.com/profphoto',
        orgId: 'fake_orgId',
        created: '2016-01-14T15:55:08.526Z',
        lastModified: '2016-01-14T15:55:08.526Z',
        type: 'person',
      },
      personId: 'fake_personId',
      phrase: 'hi',
    },
  },
  fileupload_no_text: {
    envelope: {
      id: 'fake_id',
      name: '2022-05-23T17:01:04.563Z_firehose',
      targetUrl: 'https://speedybot-hub.username.workers.dev',
      resource: 'messages',
      event: 'created',
      orgId: 'fake_orgId',
      createdBy: 'fake_createdBy',
      appId: 'fake_appId',
      ownedBy: 'creator',
      status: 'active',
      created: '2022-05-23T17:01:04.906Z',
      actorId: 'fake_actorId',
      data: {
        id: 'fake_id',
        roomId: 'fake_rooMid',
        roomType: 'direct',
        files: ['https://webexapis.com/v1/contents/fake_fileid'],
        personId: 'fake_personId',
        personEmail: 'fake_person@bongo.com',
        created: '2022-05-23T17:13:12.539Z',
      },
    },
    details: {
      id: 'fake_id',
      roomId: 'fake_roomId',
      roomType: 'direct',
      files: ['https://webexapis.com/v1/contents/fake_fileid'],
      personId: 'fake_personid',
      personEmail: 'fake_person@bongo.com',
      created: '2022-05-15T15:57:14.584Z',
    },
    trigger: {
      type: 'message',
      id: 'fake_id',
      args: [],
      message: {
        id: 'fake_message_id',
        roomId: 'fake_roomid',
        roomType: 'direct',
        files: ['https://webexapis.com/v1/contents/fake_fileId'],
        personId: 'fake_personId',
        personEmail: 'fake_person@bongo.com',
        created: '2022-05-28T13:38:25.723Z',
      },
      person: {
        id: 'fake_personId',
        emails: ['fake_person@bongo.com'],
        phoneNumbers: [
          {
            type: 'mobile',
            value: '+1 310-123-4567',
          },
          {
            type: 'work',
            value: '+1 310-654-3210',
          },
        ],
        displayName: 'Fake Person',
        nickName: 'Fake',
        firstName: 'Fake',
        lastName: 'Person',
        userName: 'fake_person@bongo.com',
        avatar: 'https://avatar-prod-us-east-2.webexcontent.com/fake_avatar',
        orgId: 'fake_orgid',
        created: '2016-01-14T15:55:08.526Z',
        lastModified: '2022-05-19T17:44:50.859Z',
        type: 'person',
      },
      personId: 'fake_personId',
    },
  },

  fileupload_with_text: {
    envelope: {
      id: 'fake_id',
      name: '2022-05-23T17:01:04.563Z_firehose',
      targetUrl: 'https://speedybot-hub.username.workers.dev',
      resource: 'messages',
      event: 'created',
      orgId: 'fake_orgId',
      createdBy: 'fake_createdBy',
      appId: 'fake_appId',
      ownedBy: 'creator',
      status: 'active',
      created: '2022-05-23T17:01:04.906Z',
      actorId: 'fake_actorId',
      data: {
        id: 'fake_id',
        roomId: 'fake_rooMid',
        roomType: 'direct',
        files: ['https://webexapis.com/v1/contents/fake_file_id'],
        personId: 'fake_personId',
        personEmail: 'fake_person@bongo.com',
        created: '2022-05-23T17:13:12.539Z',
      },
    },
    details: {
      id: 'fake_id',
      roomId: 'fake_roomId',
      roomType: 'direct',
      text: 'This is a fileupload WITH text',
      files: ['https://webexapis.com/v1/contents/fake_fileid'],
      personId: 'fake_personid',
      personEmail: 'fake_person@bongo.com',
      created: '2022-05-15T15:57:14.584Z',
    },
    trigger: {
      type: 'message',
      id: 'fake_id',
      text: 'fileupload with text',
      args: ['fileupload', 'with', 'text'],
      message: {
        id: 'fake_id',
        roomId: 'fake_roomid',
        roomType: 'direct',
        text: 'fileupload with text',
        files: ['https://webexapis.com/v1/contents/fake_fileId'],
        personId: 'fake_personId',
        personEmail: 'fake_person@bingo.com',
        created: '2016-05-28T13:39:46.610Z',
      },
      person: {
        id: 'fake_personId',
        emails: ['fake_person@bongo.com'],
        phoneNumbers: [
          {
            type: 'mobile',
            value: '+1 310-123-4567',
          },
          {
            type: 'work',
            value: '+1 310-654-3210',
          },
        ],
        displayName: 'Fake Person',
        nickName: 'Fake',
        firstName: 'Fake',
        lastName: 'Person',
        userName: 'fake_person@bongo.com',
        avatar: 'https://avatar-prod-us-east-2.webexcontent.com/fake_avatar',
        orgId: 'fake_orgid',
        created: '2016-01-14T15:55:08.526Z',
        lastModified: '2022-05-19T17:44:50.859Z',
        type: 'person',
      },
      personId: 'fake_personId',
    },
  },

  aa: {
    envelope: {
      id: 'fake_root_id',
      name: '2022-05-18T03:13:19.431Z_attachmentActions',
      targetUrl: 'https://helloworld.username.workers.dev/',
      resource: 'attachmentActions',
      event: 'created',
      orgId: 'fake_orgid',
      createdBy: 'fake_personId',
      appId: 'fake_appId',
      ownedBy: 'creator',
      status: 'active',
      created: '2022-05-18T03:13:19.773Z',
      actorId: 'fake_actorId',
      data: {
        id: 'fake_id',
        type: 'submit',
        messageId: 'fake_messageId',
        personId: 'fake_personid',
        roomId: 'fake_roomid',
        created: '2022-05-18T21:24:43.926Z',
      },
    },
    details: {
      id: 'fake_id',
      type: 'submit',
      messageId: 'fake_id',
      inputs: {
        inputData: 'aaa',
        mySpecialData: {
          a: 1,
          b: 2,
        },
      },
      personId:
        'Y2lzY29zcGFyazovL3VzL1BFT1BMRS9lMTEyZTQ3MC01NjkzLTQyOWMtYjU5NC1lZmFjN2VmMDNiNGU',
      roomId:
        'Y2lzY29zcGFyazovL3VzL1JPT00vNTBjNmQxMjAtOTliNS0xMWVjLTgxMmEtY2Q4NGYxN2QyZmRm',
      created: '2022-05-15T15:55:31.669Z',
    },
    trigger: {
      type: 'attachmentAction',
      id: 'fake_id',
      attachmentAction: {
        id: 'fake_id',
        type: 'submit',
        messageId: 'fake_messageId',
        inputs: {
          inputData: 'aaa',
          mySpecialData: {
            a: 1,
            b: 2,
          },
        },
        personId: 'fake_personId',
        roomId: 'fake_roomId',
        created: '2022-05-28T13:42:14.553Z',
      },
      person: {
        id: 'fake_personId',
        emails: ['fake_person@bongo.com'],
        phoneNumbers: [
          {
            type: 'mobile',
            value: '+1 310-123-4567',
          },
          {
            type: 'work',
            value: '+1 310-654-3210',
          },
        ],
        displayName: 'Fake Person',
        nickName: 'Fake',
        firstName: 'Fake',
        lastName: 'Person',
        userName: 'fake_person@bongo.com',
        avatar: 'https://avatar-prod-us-east-2.webexcontent.com/fake_avatar',
        orgId: 'fake_orgid',
        created: '2016-01-14T15:55:08.526Z',
        lastModified: '2022-05-19T17:44:50.859Z',
        type: 'person',
      },
      personId: 'fake_personId',
    },
  },
}
