# Run sanity test for PR's to deploy
name: Run Tests on PR
on:
  pull_request:
    branches:
      - deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Testrun
    steps:
      - name: Run tests (expects handlers.ts in settings/)
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: npm test
